  default:
    sqlite_db:
      database_type: sqlite
      sqlite_database:
        db_file: db/local_database.sqlite
        timeout: 5000
        pool_size: 5
    mongodb:
      database_type: mongodb
      mongodb_database:
        uri: mongodb+srv://RubyLabs:rubylabsteamwork22@rubylab1.pgl2z.mongodb.net/
        db_name: my_database
